/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module buttonmapping_26 (
    input [5:0] button_col,
    input [4:0] button_row,
    output reg [4:0] char
  );
  
  
  
  reg [10:0] coordinate;
  
  always @* begin
    coordinate[6+4-:5] = button_row;
    coordinate[0+5-:6] = button_col;
    
    case (coordinate)
      11'h041: begin
        char = 5'h01;
      end
      11'h042: begin
        char = 5'h02;
      end
      11'h044: begin
        char = 5'h03;
      end
      11'h048: begin
        char = 5'h04;
      end
      11'h050: begin
        char = 5'h05;
      end
      11'h060: begin
        char = 5'h06;
      end
      11'h081: begin
        char = 5'h07;
      end
      11'h082: begin
        char = 5'h08;
      end
      11'h084: begin
        char = 5'h09;
      end
      11'h088: begin
        char = 5'h0a;
      end
      11'h090: begin
        char = 5'h0b;
      end
      11'h0a0: begin
        char = 5'h0c;
      end
      11'h101: begin
        char = 5'h0d;
      end
      11'h102: begin
        char = 5'h0e;
      end
      11'h104: begin
        char = 5'h0f;
      end
      11'h108: begin
        char = 5'h10;
      end
      11'h110: begin
        char = 5'h11;
      end
      11'h120: begin
        char = 5'h12;
      end
      11'h201: begin
        char = 5'h13;
      end
      11'h202: begin
        char = 5'h14;
      end
      11'h204: begin
        char = 5'h15;
      end
      11'h208: begin
        char = 5'h16;
      end
      11'h210: begin
        char = 5'h17;
      end
      11'h220: begin
        char = 5'h18;
      end
      11'h401: begin
        char = 5'h19;
      end
      11'h402: begin
        char = 5'h1a;
      end
      11'h404: begin
        char = 5'h1b;
      end
      11'h408: begin
        char = 5'h1c;
      end
      11'h410: begin
        char = 5'h1d;
      end
      11'h420: begin
        char = 5'h1e;
      end
      default: begin
        char = 5'h1f;
      end
    endcase
  end
endmodule
