/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module displaymorse_18 (
    input [4:0] data,
    input [0:0] play,
    input clk,
    input rst,
    input [25:0] incr,
    output reg red_led,
    output reg [4:0] ra,
    output reg [3:0] value
  );
  
  
  
  reg [31:0] M_tmr_d, M_tmr_q = 1'h0;
  reg [4:0] M_read_d, M_read_q = 1'h0;
  reg M_signal_d, M_signal_q = 1'h0;
  localparam IDLE_state = 1'd0;
  localparam PLAY_state = 1'd1;
  
  reg M_state_d, M_state_q = IDLE_state;
  
  always @* begin
    M_state_d = M_state_q;
    M_tmr_d = M_tmr_q;
    M_read_d = M_read_q;
    M_signal_d = M_signal_q;
    
    ra = M_read_q;
    red_led = M_signal_q;
    value = M_tmr_q[26+3-:4];
    
    case (M_state_q)
      IDLE_state: begin
        red_led = 1'h0;
        M_read_d = 1'h0;
        if (play == 1'h1) begin
          M_state_d = PLAY_state;
        end
      end
      PLAY_state: begin
        M_tmr_d = M_tmr_q + incr;
        if (play == 1'h0) begin
          M_state_d = IDLE_state;
        end
        
        case (data)
          5'h01: begin
            
            case (M_tmr_q[26+4-:5])
              4'h0: begin
                M_signal_d = 1'h1;
              end
              4'h1: begin
                M_signal_d = 1'h0;
              end
              4'h2: begin
                M_signal_d = 1'h1;
              end
              4'h5: begin
                M_signal_d = 1'h0;
              end
              4'h8: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h02: begin
            
            case (M_tmr_q[26+4-:5])
              4'h0: begin
                M_signal_d = 1'h1;
              end
              4'h3: begin
                M_signal_d = 1'h0;
              end
              4'h4: begin
                M_signal_d = 1'h1;
              end
              4'h5: begin
                M_signal_d = 1'h0;
              end
              4'h6: begin
                M_signal_d = 1'h1;
              end
              4'h7: begin
                M_signal_d = 1'h0;
              end
              4'h8: begin
                M_signal_d = 1'h1;
              end
              4'h9: begin
                M_signal_d = 1'h0;
              end
              4'hc: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h03: begin
            
            case (M_tmr_q[26+4-:5])
              4'h0: begin
                M_signal_d = 1'h1;
              end
              4'h3: begin
                M_signal_d = 1'h0;
              end
              4'h4: begin
                M_signal_d = 1'h1;
              end
              4'h5: begin
                M_signal_d = 1'h0;
              end
              4'h6: begin
                M_signal_d = 1'h1;
              end
              4'h9: begin
                M_signal_d = 1'h0;
              end
              4'ha: begin
                M_signal_d = 1'h1;
              end
              4'hb: begin
                M_signal_d = 1'h0;
              end
              4'he: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h04: begin
            
            case (M_tmr_q[26+4-:5])
              4'h0: begin
                M_signal_d = 1'h1;
              end
              4'h3: begin
                M_signal_d = 1'h0;
              end
              4'h4: begin
                M_signal_d = 1'h1;
              end
              4'h5: begin
                M_signal_d = 1'h0;
              end
              4'h6: begin
                M_signal_d = 1'h1;
              end
              4'h7: begin
                M_signal_d = 1'h0;
              end
              4'ha: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h05: begin
            
            case (M_tmr_q[26+4-:5])
              4'h0: begin
                M_signal_d = 1'h1;
              end
              4'h1: begin
                M_signal_d = 1'h0;
              end
              4'h4: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h06: begin
            
            case (M_tmr_q[26+4-:5])
              4'h0: begin
                M_signal_d = 1'h1;
              end
              4'h1: begin
                M_signal_d = 1'h0;
              end
              4'h2: begin
                M_signal_d = 1'h1;
              end
              4'h3: begin
                M_signal_d = 1'h0;
              end
              4'h4: begin
                M_signal_d = 1'h1;
              end
              4'h7: begin
                M_signal_d = 1'h0;
              end
              4'h8: begin
                M_signal_d = 1'h1;
              end
              4'h9: begin
                M_signal_d = 1'h0;
              end
              4'hc: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h07: begin
            
            case (M_tmr_q[26+4-:5])
              4'h0: begin
                M_signal_d = 1'h1;
              end
              4'h3: begin
                M_signal_d = 1'h0;
              end
              4'h4: begin
                M_signal_d = 1'h1;
              end
              4'h7: begin
                M_signal_d = 1'h0;
              end
              4'h8: begin
                M_signal_d = 1'h1;
              end
              4'h9: begin
                M_signal_d = 1'h0;
              end
              4'hc: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h08: begin
            
            case (M_tmr_q[26+4-:5])
              4'h0: begin
                M_signal_d = 1'h1;
              end
              4'h1: begin
                M_signal_d = 1'h0;
              end
              4'h2: begin
                M_signal_d = 1'h1;
              end
              4'h3: begin
                M_signal_d = 1'h0;
              end
              4'h4: begin
                M_signal_d = 1'h1;
              end
              4'h5: begin
                M_signal_d = 1'h0;
              end
              4'h6: begin
                M_signal_d = 1'h1;
              end
              4'h7: begin
                M_signal_d = 1'h0;
              end
              4'ha: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h09: begin
            
            case (M_tmr_q[26+4-:5])
              4'h0: begin
                M_signal_d = 1'h1;
              end
              4'h1: begin
                M_signal_d = 1'h0;
              end
              4'h2: begin
                M_signal_d = 1'h1;
              end
              4'h3: begin
                M_signal_d = 1'h0;
              end
              4'h6: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h0a: begin
            
            case (M_tmr_q[26+4-:5])
              5'h00: begin
                M_signal_d = 1'h1;
              end
              5'h01: begin
                M_signal_d = 1'h0;
              end
              5'h02: begin
                M_signal_d = 1'h1;
              end
              5'h05: begin
                M_signal_d = 1'h0;
              end
              5'h06: begin
                M_signal_d = 1'h1;
              end
              5'h09: begin
                M_signal_d = 1'h0;
              end
              5'h0a: begin
                M_signal_d = 1'h1;
              end
              5'h0d: begin
                M_signal_d = 1'h0;
              end
              5'h10: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h0b: begin
            
            case (M_tmr_q[26+4-:5])
              4'h0: begin
                M_signal_d = 1'h1;
              end
              4'h3: begin
                M_signal_d = 1'h0;
              end
              4'h4: begin
                M_signal_d = 1'h1;
              end
              4'h5: begin
                M_signal_d = 1'h0;
              end
              4'h6: begin
                M_signal_d = 1'h1;
              end
              4'h9: begin
                M_signal_d = 1'h0;
              end
              4'hc: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h0c: begin
            
            case (M_tmr_q[26+4-:5])
              4'h0: begin
                M_signal_d = 1'h1;
              end
              4'h1: begin
                M_signal_d = 1'h0;
              end
              4'h2: begin
                M_signal_d = 1'h1;
              end
              4'h5: begin
                M_signal_d = 1'h0;
              end
              4'h6: begin
                M_signal_d = 1'h1;
              end
              4'h7: begin
                M_signal_d = 1'h0;
              end
              4'h8: begin
                M_signal_d = 1'h1;
              end
              4'h9: begin
                M_signal_d = 1'h0;
              end
              4'hc: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h0d: begin
            
            case (M_tmr_q[26+4-:5])
              4'h0: begin
                M_signal_d = 1'h1;
              end
              4'h3: begin
                M_signal_d = 1'h0;
              end
              4'h4: begin
                M_signal_d = 1'h1;
              end
              4'h7: begin
                M_signal_d = 1'h0;
              end
              4'ha: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h0e: begin
            
            case (M_tmr_q[26+4-:5])
              5'h00: begin
                M_signal_d = 1'h1;
              end
              5'h03: begin
                M_signal_d = 1'h0;
              end
              5'h04: begin
                M_signal_d = 1'h1;
              end
              5'h05: begin
                M_signal_d = 1'h0;
              end
              5'h08: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h0f: begin
            
            case (M_tmr_q[26+4-:5])
              5'h00: begin
                M_signal_d = 1'h1;
              end
              5'h03: begin
                M_signal_d = 1'h0;
              end
              5'h04: begin
                M_signal_d = 1'h1;
              end
              5'h07: begin
                M_signal_d = 1'h0;
              end
              5'h08: begin
                M_signal_d = 1'h1;
              end
              5'h0b: begin
                M_signal_d = 1'h0;
              end
              5'h0e: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h10: begin
            
            case (M_tmr_q[26+4-:5])
              5'h00: begin
                M_signal_d = 1'h1;
              end
              5'h01: begin
                M_signal_d = 1'h0;
              end
              5'h02: begin
                M_signal_d = 1'h1;
              end
              5'h05: begin
                M_signal_d = 1'h0;
              end
              5'h06: begin
                M_signal_d = 1'h1;
              end
              5'h09: begin
                M_signal_d = 1'h0;
              end
              5'h0a: begin
                M_signal_d = 1'h1;
              end
              5'h0b: begin
                M_signal_d = 1'h0;
              end
              5'h0e: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h11: begin
            
            case (M_tmr_q[26+4-:5])
              5'h00: begin
                M_signal_d = 1'h1;
              end
              5'h03: begin
                M_signal_d = 1'h0;
              end
              5'h04: begin
                M_signal_d = 1'h1;
              end
              5'h07: begin
                M_signal_d = 1'h0;
              end
              5'h08: begin
                M_signal_d = 1'h1;
              end
              5'h09: begin
                M_signal_d = 1'h0;
              end
              5'h0a: begin
                M_signal_d = 1'h1;
              end
              5'h0d: begin
                M_signal_d = 1'h0;
              end
              5'h11: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h12: begin
            
            case (M_tmr_q[26+4-:5])
              5'h00: begin
                M_signal_d = 1'h1;
              end
              5'h01: begin
                M_signal_d = 1'h0;
              end
              5'h02: begin
                M_signal_d = 1'h1;
              end
              5'h05: begin
                M_signal_d = 1'h0;
              end
              5'h06: begin
                M_signal_d = 1'h1;
              end
              5'h07: begin
                M_signal_d = 1'h0;
              end
              5'h0a: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h13: begin
            
            case (M_tmr_q[26+4-:5])
              5'h00: begin
                M_signal_d = 1'h1;
              end
              5'h01: begin
                M_signal_d = 1'h0;
              end
              5'h02: begin
                M_signal_d = 1'h1;
              end
              5'h03: begin
                M_signal_d = 1'h0;
              end
              5'h04: begin
                M_signal_d = 1'h1;
              end
              5'h05: begin
                M_signal_d = 1'h0;
              end
              5'h08: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h14: begin
            
            case (M_tmr_q[26+4-:5])
              5'h00: begin
                M_signal_d = 1'h1;
              end
              5'h03: begin
                M_signal_d = 1'h0;
              end
              5'h06: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h15: begin
            
            case (M_tmr_q[26+4-:5])
              5'h00: begin
                M_signal_d = 1'h1;
              end
              5'h01: begin
                M_signal_d = 1'h0;
              end
              5'h02: begin
                M_signal_d = 1'h1;
              end
              5'h03: begin
                M_signal_d = 1'h0;
              end
              5'h04: begin
                M_signal_d = 1'h1;
              end
              5'h07: begin
                M_signal_d = 1'h0;
              end
              5'h0a: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h16: begin
            
            case (M_tmr_q[26+4-:5])
              5'h00: begin
                M_signal_d = 1'h1;
              end
              5'h01: begin
                M_signal_d = 1'h0;
              end
              5'h02: begin
                M_signal_d = 1'h1;
              end
              5'h03: begin
                M_signal_d = 1'h0;
              end
              5'h04: begin
                M_signal_d = 1'h1;
              end
              5'h05: begin
                M_signal_d = 1'h0;
              end
              5'h06: begin
                M_signal_d = 1'h1;
              end
              5'h09: begin
                M_signal_d = 1'h0;
              end
              5'h0c: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h17: begin
            
            case (M_tmr_q[26+4-:5])
              5'h00: begin
                M_signal_d = 1'h1;
              end
              5'h01: begin
                M_signal_d = 1'h0;
              end
              5'h02: begin
                M_signal_d = 1'h1;
              end
              5'h05: begin
                M_signal_d = 1'h0;
              end
              5'h06: begin
                M_signal_d = 1'h1;
              end
              5'h09: begin
                M_signal_d = 1'h0;
              end
              5'h0c: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h18: begin
            
            case (M_tmr_q[26+4-:5])
              5'h00: begin
                M_signal_d = 1'h1;
              end
              5'h03: begin
                M_signal_d = 1'h0;
              end
              5'h04: begin
                M_signal_d = 1'h1;
              end
              5'h05: begin
                M_signal_d = 1'h0;
              end
              5'h06: begin
                M_signal_d = 1'h1;
              end
              5'h07: begin
                M_signal_d = 1'h0;
              end
              5'h08: begin
                M_signal_d = 1'h1;
              end
              5'h0b: begin
                M_signal_d = 1'h0;
              end
              5'h0e: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h19: begin
            
            case (M_tmr_q[26+4-:5])
              5'h00: begin
                M_signal_d = 1'h1;
              end
              5'h03: begin
                M_signal_d = 1'h0;
              end
              5'h04: begin
                M_signal_d = 1'h1;
              end
              5'h05: begin
                M_signal_d = 1'h0;
              end
              5'h06: begin
                M_signal_d = 1'h1;
              end
              5'h09: begin
                M_signal_d = 1'h0;
              end
              5'h0a: begin
                M_signal_d = 1'h1;
              end
              5'h0d: begin
                M_signal_d = 1'h0;
              end
              5'h11: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h1a: begin
            
            case (M_tmr_q[26+4-:5])
              5'h00: begin
                M_signal_d = 1'h1;
              end
              5'h03: begin
                M_signal_d = 1'h0;
              end
              5'h04: begin
                M_signal_d = 1'h1;
              end
              5'h07: begin
                M_signal_d = 1'h0;
              end
              5'h08: begin
                M_signal_d = 1'h1;
              end
              5'h09: begin
                M_signal_d = 1'h0;
              end
              5'h0a: begin
                M_signal_d = 1'h1;
              end
              5'h0b: begin
                M_signal_d = 1'h0;
              end
              5'h0e: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          5'h1b: begin
            
            case (M_tmr_q[26+4-:5])
              5'h00: begin
                M_signal_d = 1'h0;
              end
              5'h04: begin
                M_read_d = M_read_q + 1'h1;
                M_tmr_d = 1'h0;
              end
            endcase
          end
          default: begin
            M_read_d = M_read_q + 1'h1;
            M_tmr_d = 1'h0;
          end
        endcase
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_tmr_q <= 1'h0;
      M_read_q <= 1'h0;
      M_signal_q <= 1'h0;
      M_state_q <= 1'h0;
    end else begin
      M_tmr_q <= M_tmr_d;
      M_read_q <= M_read_d;
      M_signal_q <= M_signal_d;
      M_state_q <= M_state_d;
    end
  end
  
endmodule
